title: Domain Fool
description: Expertly Curated Domaining Tools & Resources for Professional Domainers. No BS.
show_downloads: true
google_analytics:
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
