title: Domain Fool
description: Expertly Curated Domaining Tools for Professional Domainers. No BS.
show_downloads: true
google_analytics:
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
github:
  zip_url: https://brandbucket.com/profile/brandmaker
  tar_url: https://opensea.io/brandmaker
